###########################################################################################################################
# Playbook: For docker-toolbox setup
###########################################################################################################################

---
- name: Setup docker toolbox
  hosts: docker_hosts
  tasks:
    - include_role:
        name: './docker-compose-updater/ansible-role'
